apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: kaniko-agent
spec:
  containers:
    - name: node
      image: node:20-alpine
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      # ❌ Pas de command
      # ❌ Pas d'args
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: workspace-volume
          mountPath: /workspace

  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
    - name: workspace-volume
      emptyDir: {}
